In [3]:
import os
import pandas as pd

In [2]:
os.listdir("../datasets/")

['2019_Aida_niños_ Microbioma Parasitos y Salud_ FINAL.xlsx',
 '41564_2018_337_MOESM4_ESM.xlsx',
 'Base_MinEEG&Macronutrientes_7abril2020.xlsx',
 'BdD - AdultosMontañaAltadeGuerrero.xlsx',
 "BdD - HOMBRES ME'PHAA.xlsx",
 'BdD - Latinbiota.xlsx',
 'BdD - MICROBIOMA ADULTOS.xlsx',
 'BdD - Microbiota Niños ciudad vs Montaña.xlsx',
 'BdD - Proyecto Microbioma V.1.xlsx',
 'BdD - Proyectos Neuroecología.xlsx',
 'BdD-2024_Metadatos_Familias_Latinbiota.xlsx',
 'bracken_taxonomy.csv',
 'Datos encuestas Nutricionales_Ciudad .xlsx',
 'ec-predictions',
 'EEG_Nutrición_Niños_C y M_2022_RevCristian.xlsx',
 'Jesus Monteros_EEG_Nutricion Niños_Ciudad_y_Montaña.csv',
 'latinbiota_pathabundance_stratified.tsv',
 'latinbiota_pathabundance_unstratified.tsv',
 'metadata_LATINBIOTA_MEXICO.xlsx',
 'module-prediction-human-01',
 'module-prediction-humann',
 'module-prediction-humann-binary',
 'module-prediction-humann-final',
 'module-prediction-KO-and-COG',
 'module-prediction2',
 'module-prediction3',
 'module-predictions',
 'taxonomy_table_otus.csv']

In [87]:
metadata = pd.read_excel("../datasets/metadata_LATINBIOTA_MEXICO.xlsx", sheet_name='Data')

In [88]:
metadata

,Run,Lane,Sample,Supplier Name,Public Name,Read count,Sample.1,Study,Health state,Disease name,BMI,Antibiotics,Age,Age group,Gender,Lifestyle,Country,Continent
0,37082_3_9,37082_3#9,GI1_LA9438076,50,47,18623506,37082_3_9,Latinbiota,Healthy,NaN,18.1,NaN,7.0,Child,Male,Rural,Mexico,North America
1,37082_3_8,37082_3#8,GI1_LA9438075,49,76,27292796,37082_3_8,Latinbiota,Healthy,NaN,18.7,NaN,9.0,Child,Male,Rural,Mexico,North America
2,37082_3_7,37082_3#7,GI1_LA9438074,47,73,23589062,37082_3_7,Latinbiota,Healthy,NaN,23.5,NaN,23.0,Adult,Female,Rural,Mexico,North America
3,37082_3_6,37082_3#6,GI1_LA9438073,76,161,17556434,37082_3_6,Latinbiota,Healthy,NaN,14.9,NaN,6.0,Child,Male,Rural,Mexico,North America
4,37082_3_5,37082_3#5,GI1_LA9438072,73,159,23119984,37082_3_5,Latinbiota,Healthy,NaN,26.5,NaN,30.0,Adult,Female,Rural,Mexico,North America
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,36703_3_13,36703_3#13,GI1_LA9438059,29,8,21839274,36703_3_13,Latinbiota,Healthy,NaN,23.8,NaN,32.0,Adult,Female,Rural,Mexico,North America
204,36703_3_12,36703_3#12,GI1_LA9438052,22,21,20889370,36703_3_12,Latinbiota,Healthy,NaN,25.6,NaN,10.0,Child,Female,Rural,Mexico,North America
205,36703_3_11,36703_3#11,GI1_LA9438050,B18,B17,21384690,36703_3_11,Latinbiota,Healthy,NaN,17.0,NaN,2.0,Infant,Male,Rural,Mexico,North America
206,36703_3_10,36703_3#10,GI1_LA9438043,C69,C68,21100234,36703_3_10,Latinbiota,Healthy,NaN,15.6,NaN,5.0,Child,Female,Urban,Mexico,North America
207,36703_3_1,36703_3#1,GI1_LA9438020,C37,C36,19849172,36703_3_1,Latinbiota,Healthy,NaN,27.9,NaN,43.0,Adult,Female,Urban,Mexico,North America

In [119]:
familias = pd.read_excel("../datasets/BdD-2024_Metadatos_Familias_Latinbiota.xlsx", sheet_name='metadatos', dtype={"BMI": float})

In [120]:
familias

,Run,Lane,Sample,Supplier Name,Public Name,Read count,Sample.1,Código,Familia,parentezco,total de parientes recolectados por familia,Disease name,BMI,Antibiotics,Age,Age group,Gender,Lifestyle,Country
0,37035_7_8,37035_7#8,GI1_LA9825327,179,179,23377132,37035_7_8,G016P,16,papá,1.0,NaN,21.6,NaN,42.0,Adult,Male,Rural,Mexico
1,37035_7_13,37035_7#13,GI1_LA9825332,182,182,21782104,37035_7_13,G028P,28,papá,1.0,NaN,25.0,NaN,28.0,Adult,Male,Rural,Mexico
2,37035_7_20,37035_7#20,GI1_LA9825339,184,184,26060218,37035_7_20,G033P,33,papá,1.0,NaN,NaN,NaN,NaN,Adult,NaN,Rural,Mexico
3,37035_7_3,37035_7#3,GI1_LA9825322,168,168,23441018,37035_7_3,N048P,48,papá,1.0,NaN,19.8,NaN,17.0,Teenager,Male,Rural,Mexico
4,37035_7_5,37035_7#5,GI1_LA9825324,169,169,24558130,37035_7_5,N058P,58,papá,1.0,NaN,25.1,NaN,32.0,Adult,Male,Rural,Mexico
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,37035_1_7,37035_1#7,GI1_LA9438116,B25,180,20632510,37035_1_7,M,trinomoio 5,NaN,4.0,NaN,25.0,NaN,24.0,Adult,Female,Rural,Mexico
204,37082_3_25,37082_3#25,GI1_LA9438098,B3,B34,19149830,37082_3_25,B3,51,hij@,3.0,NaN,2.1,NaN,3.0,Infant,Female,Rural,Mexico
205,37035_7_15,37035_7#15,GI1_LA9825334,191,191,20178234,37035_7_15,191,NaN,NaN,NaN,NaN,22.8,NaN,47.0,Adult,Male,Rural,Mexico
206,37035_7_1,37035_7#1,GI1_LA9825320,T13,T13,20787498,37035_7_1,T13,NaN,NaN,NaN,NaN,15.2,NaN,10.0,Child,Female,Rural,Mexico
207,37035_1_18,37035_1#18,GI1_LA9438130,T1,95,25732330,37035_1_18,T1,NaN,NaN,NaN,NaN,28.4,NaN,25.0,Adult,Female,Rural,Mexico

In [92]:
familias.columns

Index(['Run', 'Lane', 'Sample', 'Supplier Name', 'Public Name', 'Read count',
       'Sample.1', 'Código', 'Familia', 'parentezco',
       'total de parientes recolectados por familia', 'Disease name', 'BMI',
       'Antibiotics', 'Age', 'Age group', 'Gender', 'Lifestyle', 'Country'],
      dtype='object')

In [93]:
metadata.columns

Index(['Run', 'Lane', 'Sample', 'Supplier Name', 'Public Name', 'Read count',
       'Sample.1', 'Study', 'Health state', 'Disease name', 'BMI',
       'Antibiotics', 'Age', 'Age group', 'Gender', 'Lifestyle', 'Country',
       'Continent'],
      dtype='object')

In [20]:
metadata[metadata['Supplier Name'] == 'B25']

,Run,Lane,Sample,Supplier Name,Public Name,Read count,Sample.1,Study,Health state,Disease name,BMI,Antibiotics,Age,Age group,Gender,Lifestyle,Country,Continent
147,37035_1_7,37035_1#7,GI1_LA9438116,B25,180,20632510,37035_1_7,Latinbiota,Healthy,NaN,25.0,NaN,24.0,Adult,Female,Rural,Mexico,North America

In [19]:
familias[familias['Supplier Name'] == 'B25']

,Run,Lane,Sample,Supplier Name,Public Name,Read count,Sample.1,Código,Familia,parentezco,total de parientes recolectados por familia,Disease name,BMI,Antibiotics,Age,Age group,Gender,Lifestyle,Country
203,37035_1_7,37035_1#7,GI1_LA9438116,B25,180,20632510,37035_1_7,M,trinomoio 5,NaN,4.0,NaN,25,NaN,24.0,Adult,Female,Rural,Mexico

In [113]:
adultos = pd.read_excel("../datasets/BdD - AdultosMontañaAltadeGuerrero.xlsx", sheet_name=0)

In [114]:
adultos.columns

Index(['CODIGO ', 'Nombre', 'Edad', 'Sexo', 'QP1', 'QP2', 'QP3', 'QP4', 'QP5',
       'QP6', 'QP6b', 'QP7', 'QP7B', 'QP9', 'QP10', 'PESO', 'ALTURA', 'IMC',
       'CINTURA (PROMEDIO)', 'CADERA(PROMEDIO', '%GRASA', '%MUSCULO',
       'GRASA VISCERAL'],
      dtype='object')

In [121]:
merged = familias.merge(adultos, how='left', left_on='Código', right_on='CODIGO ')

In [116]:
merged

,Run,Lane,Sample,Supplier Name,Public Name,Read count,Sample.1,Código,Familia,parentezco,...,QP9,QP10,PESO,ALTURA,IMC,CINTURA (PROMEDIO),CADERA(PROMEDIO,%GRASA,%MUSCULO,GRASA VISCERAL
0,37035_7_8,37035_7#8,GI1_LA9825327,179,179,23377132,37035_7_8,G016P,16,papá,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,37035_7_13,37035_7#13,GI1_LA9825332,182,182,21782104,37035_7_13,G028P,28,papá,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,37035_7_20,37035_7#20,GI1_LA9825339,184,184,26060218,37035_7_20,G033P,33,papá,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,37035_7_3,37035_7#3,GI1_LA9825322,168,168,23441018,37035_7_3,N048P,48,papá,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,37035_7_5,37035_7#5,GI1_LA9825324,169,169,24558130,37035_7_5,N058P,58,papá,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,37035_1_7,37035_1#7,GI1_LA9438116,B25,180,20632510,37035_1_7,M,trinomoio 5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,37082_3_25,37082_3#25,GI1_LA9438098,B3,B34,19149830,37082_3_25,B3,51,hij@,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,37035_7_15,37035_7#15,GI1_LA9825334,191,191,20178234,37035_7_15,191,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,37035_7_1,37035_7#1,GI1_LA9825320,T13,T13,20787498,37035_7_1,T13,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,37035_1_18,37035_1#18,GI1_LA9438130,T1,95,25732330,37035_1_18,T1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
metadata[metadata['Lane'] == '37082_2#22']

,Run,Lane,Sample,Supplier Name,Public Name,Read count,Sample.1,Study,Health state,Disease name,BMI,Antibiotics,Age,Age group,Gender,Lifestyle,Country,Continent
49,37082_2_22,37082_2#22,GI1_LA9438051,21,B18,22742148,37082_2_22,Latinbiota,Healthy,NaN,27.6,NaN,23.0,Adult,Female,Rural,Mexico,North America

In [65]:
familias[familias['Código'] == 'G068P']

Empty DataFrame
Columns: [Run, Lane, Sample, Supplier Name, Public Name, Read count, Sample.1, Código, Familia, parentezco, total de parientes recolectados por familia, Disease name, BMI, Antibiotics, Age, Age group, Gender, Lifestyle, Country]
Index: []

In [53]:
adultos[adultos['CODIGO '] == 'G0102M']

,CODIGO,Nombre,Edad,Sexo,QP1,QP2,QP3,QP4,QP5,QP6,...,QP9,QP10,PESO,ALTURA,IMC,CINTURA (PROMEDIO),CADERA(PROMEDIO,%GRASA,%MUSCULO,GRASA VISCERAL
15,G0102M,IIDALIA JAZMYN SANTIAGO GARCIA,31,M,4,2,5,2,3,0,...,4,4,43.7,1.49,19.683798,73.3,90.6,2019-04-27 00:00:00,2019-06-27 00:00:00,3

In [59]:
for cod in list(adultos['CODIGO ']):
    # a = familias[familias['Código'] == cod].iloc[0]
    # b = adultos[adultos['CODIGO '] == cod].iloc[0]
    # print(a, b)
    try:
        if familias[familias['Código'] == cod]['Age'].iloc[0] != adultos[adultos['CODIGO '] == cod]['Edad'].iloc[0]:
            lane = familias[familias['Código'] == cod]['Lane'].iloc[0]
            # print(lane)
            print(f"{metadata[metadata['Lane'] == lane]['Age'].iloc[0]}, {adultos[adultos['CODIGO '] == cod]['Edad'].iloc[0]}")
            print('EDADES DIFERENTES: ', cod, lane)
    except:
        pass

23.0, 21
EDADES DIFERENTES:  N056M 37082_2#22
nan, 48
EDADES DIFERENTES:  G006M 37035_7#17
30.0, 29
EDADES DIFERENTES:  G030P 36703_3#25
42.0, 41
EDADES DIFERENTES:  G045P 37035_1#13
27.0, 26
EDADES DIFERENTES:  N069P 37035_7#7

In [99]:
adultos_mephaa = pd.read_excel("../datasets/BdD - HOMBRES ME'PHAA.xlsx", sheet_name=0)

In [100]:
adultos_mephaa.head()

,CODIGO 2016,Unnamed: 1,EDAD,SEXO,ALTURA,PESO,%GRASA,%MUSCULO,GRASA VISCERAL,CINT1,...,QP9,QP10,2D:4D,FOTO,MUESTRA SALIVA,horas antes de la ultima comida,Peridontitis,KIT,# HUEVOS,ESPECIE
0,N048P,ONESIMO RODRIGUEZ AMADO,18,H,NaN,NaN,NaN,NaN,NaN,NaN,...,SEGUIDO,NO MUY SEGUIDO,NaN,NaN,NaN,12,3.0,NaN,NaN,NaN
1,N058P,MARTIN AURELIO CATARINA,32,H,NaN,NaN,NaN,NaN,NaN,NaN,...,CASI NUNCA,REGULAR,SI,SI,NaN,4,3.0,NaN,NaN,NaN
2,N060P,MARCELINO RUIZ RODRIGUEZ,39,H,1.49,57.3,28.0,34.0,11.0,NaN,...,REGULAR,REGULAR,SI,SI,SI,1,4.0,NaN,NaN,NaN
3,G068P,EULALIO EMILIANO GARCIA,26,H,167.00,59.2,16.4,41.8,2.0,79.0,...,NaN,NaN,SI,G068P,ST,28min,3.0,NaN,NaN,NaN
4,N069P,ANSELMO RUBIO SANTIAGO,27,H,1.58,72.5,30.0,35.6,11.0,NaN,...,3,3,SI,SI,SI,3,3.0,NaN,NaN,NaN

In [71]:
for cod in list(adultos_mephaa['CODIGO 2016']):
    # a = familias[familias['Código'] == cod].iloc[0]
    # b = adultos[adultos['CODIGO '] == cod].iloc[0]
    # print(a, b)
    try:
        if familias[familias['Código'] == cod]['Age'].iloc[0] != adultos_mephaa[adultos_mephaa['CODIGO 2016'] == cod]['EDAD'].iloc[0]:
            # print(cod)
            lane = familias[familias['Código'] == cod]['Lane'].iloc[0]
            # print(lane)
            # print(f"{metadata[metadata['Lane'] == lane]['Age'].iloc[0]}, {adultos_mephaa[adultos_mephaa['CODIGO 2016'] == cod]['EDAD'].iloc[0]}")
            # print('EDADES DIFERENTES: ', cod, lane)
    except:
        print(cod)

N060P
G068P
N133P
N135P
N137P
N139P
G112P
G114P
G115P
G116P
G117P
G029P
G034P
G068P
G081P
G102P

In [122]:
merged2 = merged.merge(adultos_mephaa, how='left', left_on='Código', right_on='CODIGO 2016')

In [103]:
merged2

,Run,Lane,Sample,Supplier Name,Public Name,Read count,Sample.1,Código,Familia,parentezco,...,QP9_y,QP10_y,2D:4D,FOTO,MUESTRA SALIVA,horas antes de la ultima comida,Peridontitis,KIT,# HUEVOS,ESPECIE
0,37035_7_8,37035_7#8,GI1_LA9825327,179,179,23377132,37035_7_8,G016P,16,papá,...,0,0,SI,SI,SI,3,5.0,SI,NaN,NaN
1,37035_7_13,37035_7#13,GI1_LA9825332,182,182,21782104,37035_7_13,G028P,28,papá,...,5,4,NaN,IMG53-IMG55,SI,3.3horas,3.0,Entrego,NaN,NaN
2,37035_7_20,37035_7#20,GI1_LA9825339,184,184,26060218,37035_7_20,G033P,33,papá,...,3,4,NaN,G033P,SI,30,1.0,Entrego,NaN,NaN
3,37035_7_3,37035_7#3,GI1_LA9825322,168,168,23441018,37035_7_3,N048P,48,papá,...,SEGUIDO,NO MUY SEGUIDO,NaN,NaN,NaN,12,3.0,NaN,NaN,NaN
4,37035_7_5,37035_7#5,GI1_LA9825324,169,169,24558130,37035_7_5,N058P,58,papá,...,CASI NUNCA,REGULAR,SI,SI,NaN,4,3.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,37035_1_7,37035_1#7,GI1_LA9438116,B25,180,20632510,37035_1_7,M,trinomoio 5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,37082_3_25,37082_3#25,GI1_LA9438098,B3,B34,19149830,37082_3_25,B3,51,hij@,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,37035_7_15,37035_7#15,GI1_LA9825334,191,191,20178234,37035_7_15,191,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,37035_7_1,37035_7#1,GI1_LA9825320,T13,T13,20787498,37035_7_1,T13,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,37035_1_18,37035_1#18,GI1_LA9438130,T1,95,25732330,37035_1_18,T1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
adultos

,CODIGO,Nombre,Edad,Sexo,QP1,QP2,QP3,QP4,QP5,QP6,...,QP9,QP10,PESO,ALTURA,IMC,CINTURA (PROMEDIO),CADERA(PROMEDIO,%GRASA,%MUSCULO,GRASA VISCERAL
0,N056M,ALICIA GARCIA ESPINOZA,21,M,5,5,4,4,4,1,...,4,5,58.0,1.45,27.586207,82.0,100.0,42.5,2019-03-25 00:00:00,6
1,N075M,MARCELA SATURNINO ALEJO,23,M,3,4,3,5,3,1,...,2,2,46.1,1.40,23.520408,75.0,89.0,38,26,5
2,N055M,NATALIA REMIGIO AURELIO,49,M,2,3,2,3,2,1,...,2,3,64.8,1.43,31.688591,91.0,114.0,48.4,2019-06-21 00:00:00,10
3,N047M,GUADALUPE ZAMORA ELIDIA,49,M,2,3,3,3,3,1,...,2,2,46.3,1.45,22.021403,89.0,91.0,35.4,2019-07-27 00:00:00,7
4,N079M,ISIDORA GARCIA ESPINOZA,34,M,4,4,3,3,3,1,...,2,2,62.9,1.50,27.955556,98.0,104.5,38,2019-02-27 00:00:00,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,U030M,Nayeli Avila López,35,M,2,4,4,4,4,1,...,4,2,66.8,1.59,26.423005,85.8,103.0,40.5,25.2,6
82,U027M,Alejandra Evelyn Rúiz Contrera,42,M,4,4,4,4,5,1,...,4,4,57.8,1.63,21.754676,77.0,97.8,32.2,27.5,5
83,U038M,Nadia Saraí Peña Pacheco,34,M,3,4,4,5,4,0,...,4,4,45.0,1.65,16.528926,66.5,85.6,19.2,28.4,2
84,U040M,Violeta Ayala Mexicano,43,M,4,5,4,4,3,1,...,4,4,52.2,1.49,23.512454,78.5,93.8,37.5,24.1,6
85,U030M,Nayeli Avila López,35,M,2,4,4,4,4,1,...,4,2,66.8,1.59,26.423005,85.8,103.0,40.5,25.2,6

In [104]:
adultos_microbioma = pd.read_excel("../datasets/BdD - MICROBIOMA ADULTOS.xlsx", sheet_name=0)

In [105]:
adultos_microbioma.head()

,Name,Collection Code,ID,Age,Sex,Kinship,Procedence,Height (m),Weight (kgs),BMI,Diseases (Currently),Meds Treatment (Currently),Meds Treatment (Last Month),#_parasites,Qp4,Qp5,Qp9,Qp10,Notas
0,ALICIA GARCIA ESPINOZA,N056M,21,23,M,mamá,Naranjo,1.45,58.0,27.586207,0,0,1,0,4,4,4,5,NaN
1,MARCELA SATURNINO ALEJO,N075M,47,23,M,mamá,Naranjo,1.40,46.1,23.520408,0,0,1,0,5,3,2,2,NaN
2,NATALIA REMIGIO AURELIA,N055M,26,49,M,mamá,Naranjo,1.39,61.8,31.985922,0,0,3,0,3,2,2,3,NaN
3,GUADALUPE ZAMORA ELIDIA,N047M,8,49,M,mamá,Naranjo,1.45,46.3,22.021403,0,0,1,3935,3,3,2,2,NaN
4,ISIDORA GARCIA ESPINOZA,N079M,62,34,M,mamá,Naranjo,1.50,62.9,27.955556,0,0,1,0,3,3,2,2,NaN

In [123]:
merged3 = merged2.merge(adultos_microbioma, how='left', left_on='Código', right_on='Collection Code')

In [124]:
merged3

,Run,Lane,Sample,Supplier Name,Public Name,Read count,Sample.1,Código,Familia,parentezco,...,BMI_y,Diseases (Currently),Meds Treatment (Currently),Meds Treatment (Last Month),#_parasites,Qp4,Qp5,Qp9,Qp10,Notas
0,37035_7_8,37035_7#8,GI1_LA9825327,179,179,23377132,37035_7_8,G016P,16,papá,...,21.566834,0,0,0,0.0,na,na,na,na,NaN
1,37035_7_13,37035_7#13,GI1_LA9825332,182,182,21782104,37035_7_13,G028P,28,papá,...,24.953894,0,0,0,110.0,na,na,5,4,NaN
2,37035_7_20,37035_7#20,GI1_LA9825339,184,184,26060218,37035_7_20,G033P,33,papá,...,29.121936,0,0,0,85.0,na,na,3,4,NaN
3,37035_7_3,37035_7#3,GI1_LA9825322,168,168,23441018,37035_7_3,N048P,48,papá,...,19.834711,0,0,0,15.0,3,4,4,2,cuestionario posterior
4,37035_7_5,37035_7#5,GI1_LA9825324,169,169,24558130,37035_7_5,N058P,58,papá,...,25.114772,0,0,0,5.0,4,3,4,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,37035_1_7,37035_1#7,GI1_LA9438116,B25,180,20632510,37035_1_7,M,trinomoio 5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,37082_3_25,37082_3#25,GI1_LA9438098,B3,B34,19149830,37082_3_25,B3,51,hij@,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,37035_7_15,37035_7#15,GI1_LA9825334,191,191,20178234,37035_7_15,191,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,37035_7_1,37035_7#1,GI1_LA9825320,T13,T13,20787498,37035_7_1,T13,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,37035_1_18,37035_1#18,GI1_LA9438130,T1,95,25732330,37035_1_18,T1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [111]:
merged3['BMI_x']

0      2024-06-21 00:00:00
1                       25
2                      NaN
3      2024-08-19 00:00:00
4      2024-01-25 00:00:00
              ...
203                     25
204    2024-01-02 00:00:00
205    2024-08-22 00:00:00
206    2024-02-15 00:00:00
207    2024-04-28 00:00:00
Name: BMI_x, Length: 208, dtype: object

In [125]:
merged3.to_csv('combined2.csv', index = False)

In [109]:
merged3['BMI_x'] = merged3['BMI_x'].astype(float)

TypeError: float() argument must be a string or a real number, not 'datetime.datetime'

In [80]:
for cod in list(adultos_microbioma['Collection Code']):
    # a = familias[familias['Código'] == cod].iloc[0]
    # b = adultos[adultos['CODIGO '] == cod].iloc[0]
    # print(a, b)
    try:
        if familias[familias['Código'] == cod]['Age'].iloc[0] != adultos_microbioma[adultos_microbioma['Collection Code'] == cod]['Age'].iloc[0]:
            # print(cod)
            lane = familias[familias['Código'] == cod]['Lane'].iloc[0]
            # print(lane)
            # print(f"{metadata[metadata['Lane'] == lane]['Age'].iloc[0]}, {adultos_microbioma[adultos_microbioma['Collection Code'] == cod]['Age'].iloc[0]}")
            # print('EDADES DIFERENTES: ', cod, lane)
    except:
        print(cod)
        pass

G033M
G068P
U002M
U003M
U005M
U006M
U007M
U009M
U011M
U012M
U014M
U016M

In [82]:
nutricion = pd.read_excel("../datasets/EEG_Nutrición_Niños_C y M_2022_RevCristian.xlsx", sheet_name=0)

In [86]:
[x for x in list(nutricion['ID']) if x in list(familias['Código'])]

['N055H2',
 'N079H1',
 'N060H1',
 'N078H1',
 'N073H1',
 'N050H1',
 'G045H1',
 'G042H4',
 'G046H1',
 'G025H3',
 'G013H2',
 'N075H3',
 'N056H2',
 'N056H1',
 'N075H1',
 'N075H2',
 'N056H3',
 'G030H3',
 'G105H1',
 'G105H2',
 'G013H4',
 'G020H4',
 'G006H1',
 'N055H1',
 'N054H1']

In [85]:
familias

,Run,Lane,Sample,Supplier Name,Public Name,Read count,Sample.1,Código,Familia,parentezco,total de parientes recolectados por familia,Disease name,BMI,Antibiotics,Age,Age group,Gender,Lifestyle,Country
0,37035_7_8,37035_7#8,GI1_LA9825327,179,179,23377132,37035_7_8,G016P,16,papá,1.0,NaN,2024-06-21 00:00:00,NaN,42.0,Adult,Male,Rural,Mexico
1,37035_7_13,37035_7#13,GI1_LA9825332,182,182,21782104,37035_7_13,G028P,28,papá,1.0,NaN,25,NaN,28.0,Adult,Male,Rural,Mexico
2,37035_7_20,37035_7#20,GI1_LA9825339,184,184,26060218,37035_7_20,G033P,33,papá,1.0,NaN,NaN,NaN,NaN,Adult,NaN,Rural,Mexico
3,37035_7_3,37035_7#3,GI1_LA9825322,168,168,23441018,37035_7_3,N048P,48,papá,1.0,NaN,2024-08-19 00:00:00,NaN,17.0,Teenager,Male,Rural,Mexico
4,37035_7_5,37035_7#5,GI1_LA9825324,169,169,24558130,37035_7_5,N058P,58,papá,1.0,NaN,2024-01-25 00:00:00,NaN,32.0,Adult,Male,Rural,Mexico
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,37035_1_7,37035_1#7,GI1_LA9438116,B25,180,20632510,37035_1_7,M,trinomoio 5,NaN,4.0,NaN,25,NaN,24.0,Adult,Female,Rural,Mexico
204,37082_3_25,37082_3#25,GI1_LA9438098,B3,B34,19149830,37082_3_25,B3,51,hij@,3.0,NaN,2024-01-02 00:00:00,NaN,3.0,Infant,Female,Rural,Mexico
205,37035_7_15,37035_7#15,GI1_LA9825334,191,191,20178234,37035_7_15,191,NaN,NaN,NaN,NaN,2024-08-22 00:00:00,NaN,47.0,Adult,Male,Rural,Mexico
206,37035_7_1,37035_7#1,GI1_LA9825320,T13,T13,20787498,37035_7_1,T13,NaN,NaN,NaN,NaN,2024-02-15 00:00:00,NaN,10.0,Child,Female,Rural,Mexico
207,37035_1_18,37035_1#18,GI1_LA9438130,T1,95,25732330,37035_1_18,T1,NaN,NaN,NaN,NaN,2024-04-28 00:00:00,NaN,25.0,Adult,Female,Rural,Mexico